---
title: "Get overlap of GRanges keeping metadata"
author: "Alexey Larionov"
date: "18 Feb 2021"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: 
      collapsed: false
editor_options:
  chunk_output_type: console
---

# Summary

Explore gene names  

# Start section

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r echo=F}
#options(width = 999)
```

```{r}

# Time stamp
Sys.time()

# Clenan-up
rm(list=ls())
graphics.off()

# Memory
gc()

# Options
options(stringsAsFactors=F)

# Files and folders
base_folder="/Users/alexey/Documents/mg/s2021/zhang_tests"
working_folder=file.path(base_folder,"s05_select_variants")
setwd(working_folder)

# Libraries
library(GenomicRanges)

```

# Read GRanges

## 161 genes

```{r}

load(file.path(base_folder,"s04_explore_gene_list","s03_161_gene_coordinates.RData"))
base_folder="/Users/alexey/Documents/mg/s2021/zhang_tests"
working_folder=file.path(base_folder,"s05_select_variants")

ls()
genes_161.gr

```

## Annotated variants

```{r}

load(file.path(working_folder,"s01_read_annotated_txt_to_granges.RData"))
base_folder="/Users/alexey/Documents/mg/s2021/zhang_tests"
working_folder=file.path(base_folder,"s05_select_variants")

ls()
summary(data.gr)
data.gr[,1:3]

# Explore metadata
names(data.gr@elementMetadata)

```

# Select variants in 161 genes

## Example of GR subset by overlap

Taken from ?subsetByOverlaps

```{r}

# Make toy GRanges
gr <- GRanges(
        seqnames=Rle(c("chr1", "chr2", "chr1", "chr3"), c(1, 3, 2, 4)),
        ranges=IRanges(1:10, width=10:1, names=head(letters,10)),
        strand=Rle(strand(c("-", "+", "*", "+", "-")), c(1, 2, 2, 3, 2)),
        score=1:10,
        GC=seq(1, 0, length=10)
      )

gr1 <- GRanges(seqnames="chr2", ranges=IRanges(4:3, 6),
               strand="+", score=5:4, GC=0.45)

# Get gr elements that overlap with gr1
gr
gr1
subsetByOverlaps(gr, gr1)

# Clean-up
rm(gr,gr1)

```

## Variants overlapping 161 genes

```{r}

# Get variants by overlap
# see details in ?subsetByOverlaps
# note that the default overlap type is "any"
variants_161_genes.gr <- subsetByOverlaps(data.gr, genes_161.gr, type="any")

# Explore result
summary(variants_161_genes.gr)

options(showHeadLines=500)
options(showTailLines=500)
variants_161_genes.gr[,c("Gene.refGene","Func.refGene","ExonicFunc.refGene")]
options(showHeadLines=NULL)
options(showTailLines=NULL)

# Clean-up
rm(data.gr,genes_161.gr)

```

```{r}

save.image("s02_select_161_gene_variants.RData")

```

# Final section

```{r}

ls()
sessionInfo()
Sys.time()
gc()

```
