---
title: "Test1"
author: "AL"
date: "22/02/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages

```{r}

library(VennDiagram)

#BiocManager::install("org.Hs.eg.db")
library(org.Hs.eg.db)

#BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")
library(TxDb.Hsapiens.UCSC.hg38.knownGene)

```

# Read entrez id-s from genes and transcripts databases

```{r}

# Gene names
org.b38 <- org.Hs.eg.db
entrez2symbols.df <- select(org.b38,
            keys=keys(org.b38,"ENTREZID"),
            columns=c("SYMBOL","ENTREZID"),
            keytype="ENTREZID")

dim(entrez2symbols.df)
head(entrez2symbols.df)

# Transcripts
tx.b38 <- TxDb.Hsapiens.UCSC.hg38.knownGene
tx.b38
entrez_id_tx.df <- select(tx.b38,
            keys=keys(tx.b38,"GENEID"),
            columns=c("GENEID"),
            keytype="GENEID")

dim(entrez_id_tx.df)
head(entrez_id_tx.df)

```

# Check duplicated and missed 

```{r}

# Gene names
sum(duplicated(entrez2symbols.df$ENTREZID))
sum(duplicated(entrez2symbols.df$SYMBOL))

# Transcripts 
sum(duplicated(entrez_id_tx.df$GENEID))

```

# Compare Tx and Genes databases

```{r}

x <- setdiff(entrez_id_tx.df$GENEID,entrez2symbols.df$ENTREZID)
length(x)
x

y <- intersect(entrez_id_tx.df$GENEID,entrez2symbols.df$ENTREZID)
length(y)

z <- venn.diagram(list(tx_db=entrez_id_tx.df$GENEID,
                  org_db=entrez2symbols.df$ENTREZID),
             filename=NULL);

grid.draw(z)

rm(x,y,z)

```

# Web example

https://support.bioconductor.org/p/81083/ 

```{r}



```

